# =========================================================================
#  UniFi Vsratiy PBR-VPN-PROXYFI — CONFIGURATION FILE
# =========================================================================
ROUTE_MODE="smart-fallback"
TARGET_INTERFACE="TEMPLATE_IFACE"

# Автоматически подобранные уникальные маркеры firewall
FWMARK_WARP="TEMPLATE_FWMARK_WARP"
FWMARK_PROXY="TEMPLATE_FWMARK_PROXY"

# Настройки резервного прокси-канала
USE_PROXY="TEMPLATE_USE_PROXY"
PROXY_TYPE="TEMPLATE_PROXY_TYPE"
PROXY_IP="TEMPLATE_PROXY_IP"
PROXY_PORT="TEMPLATE_PROXY_PORT"
PROXY_USER="TEMPLATE_PROXY_USER"
PROXY_PASS="TEMPLATE_PROXY_PASS"

# Золотой список доменов для обхода ограничений
DOMAINS="ui.com ubnt.com amazonaws.com ips.svc.ui.com mtls-security.svc.ui.com nca-iot-us-west-2.svc.ui.com apt.artifacts.ui.com fw-download.ubnt.com fw-update.ubnt.com"

# Настройки уведомлений в Telegram (Оставьте пустыми, если не нужно)
TG_BOT_TOKEN="TEMPLATE_TG_BOT_TOKEN"
TG_CHAT_ID="TEMPLATE_TG_CHAT_ID"

# Настройки Микро-Email через встроенный Python (Оставьте пустыми, если не нужно)
EMAIL_ENABLED="TEMPLATE_EMAIL_ENABLED"
SMTP_SERVER="TEMPLATE_SMTP_SERVER"
SMTP_PORT="TEMPLATE_SMTP_PORT"
SMTP_USER="TEMPLATE_SMTP_USER"
SMTP_PASS="TEMPLATE_SMTP_PASS"
EMAIL_TO="TEMPLATE_EMAIL_TO"
